---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - neighbordiscoverer.openshift.io
  resources:
  - nodeneighbornetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - neighbordiscoverer.openshift.io
  resources:
  - nodeneighbornetworks/finalizers
  verbs:
  - update
- apiGroups:
  - neighbordiscoverer.openshift.io
  resources:
  - nodeneighbornetworks/status
  verbs:
  - get
  - patch
  - update
